name: Publish

on:
  push:
    branches:
      - stable

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: npm publish
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
